### PR TITLE
Slug fragment evaluation: Replace any leading non-characters

### PR DESCRIPTION
**Pull request by tastendruecker**
Hi Sebastian,

thanks for your pretty nice extension! There is only one thing I noticed: The slugs that are converted from the headers may contain leading non-characters what makes them possibly unfeasible as id-attribute values. So, I would like to propose a little change to the class FragmentEvaluation...

Regards
Sven

### CODE REVIEW

**Comment by sebkln** [comment]
Hi Sven, thank you for your PR! Much appreciated. I'll check the changes and then merge it.

**Comment by sebkln** [comment]
Your current approach not only removes Unicode noncharacters, but every leading character which is not in the range from A to Z. This would make it impossible to use e.g. Chinese characters as fragments (which has browser support). Can you provide a regex that **explicitly** matches the noncharacters?

**Comment by tastendruecker** [comment]
Hi Sebastian,

thanks for your feedback! As the HTML4 specs (https://www.w3.org/TR/html4/types.html#type-id) say:

>  ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

That's probably why Fluid Styled Content places a "c" before the uid of a content element to build the id attribute inside the standard Fluid layouts.

HTML5 is supposed to be more permissive regarding the id attribute. But since we don't know the doc type when saving the content element (or do we?) I'd like to be on the safe side and do the replacement in a more restrictive and HTML4 compatible way. 

Regards
Sven

**Comment by sebkln** [comment]
Hi Sven,

you're right of course. Allowed characters are pretty limited with HTML 4, and the `#c123` fragments in the TYPO3 core still consider that.

Also, the current fragment evaluation will **convert** Cyrillic characters but **keep** Chinese characters, which might be inconsistent. But this matches the Core's behaviour in the `slug` field.

I'm fine with supporting HTML 4, but I don't want to introduce new limitations for HTML5 websites (which are the vast majority).

As written before, your PR would delete a fragment like _русский_ before it can be converted to _russkii_ by the `specCharsToASCII()` method in PHP.

Under which circumstances can the header field contain leading noncharacters? Shouldn't the `trim` evaluation already remove those?

Regards, Sebastian

**Comment by tastendruecker** [comment]
Hi Sebastian,

you absolutely have a point there. My actual problem was a project, where the editors on some pages numbered their headers. That led to slugs/ids starting with numbers followed by periods like "1.foo...", "2.bar..." - invalid at least with the HTML4 doktype.

Within an HTML5 context that is of course no problem at all. So, perhaps it would be the best to only execute the proposed manipulation if an additional TypoScript option like `plugin.tx_contentslug.settings.createHtml4CompatibleSlugs` is set. What do you think?

Regards, Sven

**Comment by sebkln** [comment]
Hi Sven,

I see. But this is a different issue then.

Introducing such a TypoScript setting would mean that the TypoScript configuration must be loaded and processed each time an editor triggers the fragment evaluation (both with JS and PHP).

Also, I can think of a few follow-up questions spontaneously:
- What if the content element is shared in a multi-domain installation with different doctypes (I've seen things …)?
- What if the doctype is changed later?

Yes, these might be unlikely edge cases. I'm sorry, but I currently don't see the need to add this complexity to the extension.

In your project, you still have different options:
1. **Use your fork,** which already provides the desired behaviour. Rebasing it with future versions of this extension should be possible.
2. **Use a HTML4-compatible prefix** for the fragments.
3. **Advise your editors** to adjust the fragments (yes, I know how some editors can be).

Regards, Sebastian

**Comment by tastendruecker** [comment]
Hi Sebastian,

thanks for your advice. That's all right with me. :-)

Regards,
Sven

**Pull request closed without merging**
